/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.awt.event.WindowEvent;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.UIManager;

/**
 *
 * @author PatLas
 */
public class MainGui extends javax.swing.JFrame {
    public String fName = null;
    private ProgressDialog pd = null;
    /**
     * Creates new form MainGui
     */
    public MainGui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpCharts = new javax.swing.JTabbedPane();
        pptPane = new javax.swing.JPanel();
        pdfPane = new javax.swing.JPanel();
        moviePane = new javax.swing.JPanel();
        topMenuBar = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        mConnect = new javax.swing.JMenuItem();
        mOpenFile = new javax.swing.JMenuItem();
        mSeparator = new javax.swing.JPopupMenu.Separator();
        mExit = new javax.swing.JMenuItem();
        menuEdit = new javax.swing.JMenu();
        menuAbout = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("MainFrame"); // NOI18N
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        javax.swing.GroupLayout pptPaneLayout = new javax.swing.GroupLayout(pptPane);
        pptPane.setLayout(pptPaneLayout);
        pptPaneLayout.setHorizontalGroup(
            pptPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 395, Short.MAX_VALUE)
        );
        pptPaneLayout.setVerticalGroup(
            pptPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 245, Short.MAX_VALUE)
        );

        tpCharts.addTab("Presentation", new javax.swing.ImageIcon(getClass().getResource("/gui/icons/ppt-20.png")), pptPane, "Start PowerPoint presentation"); // NOI18N

        javax.swing.GroupLayout pdfPaneLayout = new javax.swing.GroupLayout(pdfPane);
        pdfPane.setLayout(pdfPaneLayout);
        pdfPaneLayout.setHorizontalGroup(
            pdfPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 395, Short.MAX_VALUE)
        );
        pdfPaneLayout.setVerticalGroup(
            pdfPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 245, Short.MAX_VALUE)
        );

        tpCharts.addTab("PDF", new javax.swing.ImageIcon(getClass().getResource("/gui/icons/pdf-20.png")), pdfPane, "View pdf file"); // NOI18N

        javax.swing.GroupLayout moviePaneLayout = new javax.swing.GroupLayout(moviePane);
        moviePane.setLayout(moviePaneLayout);
        moviePaneLayout.setHorizontalGroup(
            moviePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 395, Short.MAX_VALUE)
        );
        moviePaneLayout.setVerticalGroup(
            moviePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 245, Short.MAX_VALUE)
        );

        tpCharts.addTab("Movie", new javax.swing.ImageIcon(getClass().getResource("/gui/icons/mov-20.png")), moviePane, "Stream movie"); // NOI18N

        getContentPane().add(tpCharts);

        menuFile.setText("File");
        menuFile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuFile.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        mConnect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/workflow_16x16.png"))); // NOI18N
        mConnect.setText("Connect");
        mConnect.setToolTipText("");
        mConnect.setActionCommand("mConnect");
        mConnect.setNextFocusableComponent(mOpenFile);
        mConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mConnectActionPerformed(evt);
            }
        });
        menuFile.add(mConnect);
        mConnect.getAccessibleContext().setAccessibleName("mConnect");

        mOpenFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/folder_16x16.png"))); // NOI18N
        mOpenFile.setText("Open file");
        mOpenFile.setNextFocusableComponent(mExit);
        mOpenFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mOpenFileActionPerformed(evt);
            }
        });
        menuFile.add(mOpenFile);
        menuFile.add(mSeparator);

        mExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/delete_16x16.png"))); // NOI18N
        mExit.setText("Exit");
        mExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mExitActionPerformed(evt);
            }
        });
        menuFile.add(mExit);

        topMenuBar.add(menuFile);

        menuEdit.setText("Edit");
        topMenuBar.add(menuEdit);

        menuAbout.setText("About");
        topMenuBar.add(menuAbout);

        setJMenuBar(topMenuBar);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mOpenFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mOpenFileActionPerformed
       JFileChooser fileChooser = new JFileChooser();
        int returnValue = fileChooser.showOpenDialog(null);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
          File selectedFile = fileChooser.getSelectedFile();
          fName = selectedFile.getName();
          System.out.println(selectedFile.getName());
        }
    }//GEN-LAST:event_mOpenFileActionPerformed

    private void mExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mExitActionPerformed
        // TODO add your handling code here:
        if(pd != null){
            pd.pProgressBar.setValue(100);
            pd.dispatchEvent(new WindowEvent(pd, WindowEvent.WINDOW_CLOSING));
        }
        
    }//GEN-LAST:event_mExitActionPerformed

    private void mConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mConnectActionPerformed
        // TODO add your handling code here:

        GraphicsDevice gd = GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice();
        int width = gd.getDisplayMode().getWidth();
        int height = gd.getDisplayMode().getHeight();
        pd = new ProgressDialog();
        pd.setSize((int) Math.round(width*0.3), (int) Math.round(height*0.1));
        pd.pProgressBar.setValue(70);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                pd.setVisible(true);
            }
        });

        //pd.setSize(WIDTH, WIDTH);
    }//GEN-LAST:event_mConnectActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows"/*"Nimbus"*/.equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        
      
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem mConnect;
    private javax.swing.JMenuItem mExit;
    private javax.swing.JMenuItem mOpenFile;
    private javax.swing.JPopupMenu.Separator mSeparator;
    private javax.swing.JMenu menuAbout;
    private javax.swing.JMenu menuEdit;
    private javax.swing.JMenu menuFile;
    public javax.swing.JPanel moviePane;
    public javax.swing.JPanel pdfPane;
    public javax.swing.JPanel pptPane;
    private javax.swing.JMenuBar topMenuBar;
    private javax.swing.JTabbedPane tpCharts;
    // End of variables declaration//GEN-END:variables
}
